/**
 * Classic Variant — Original 15-block stack
 *
 * This is the original data from data.ts, extracted as a variant.
 * 3 levels: A (grid 2×2), B (row ×3), C (full ×8).
 * No geometry overrides — uses config.ts defaults.
 */

import type { LayerData } from '../types';
import type { StackVariant } from './types';
import { icons } from '../icons';
import { palette } from '@/config/palette';

const layers: LayerData[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // LEVEL A: TOP QUADRANTS — Anchor + Value tones
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'layer-a',
    level: 'A',
    layout: 'grid',
    cols: 2,
    rows: 2,
    blocks: [
      {
        id: 0,
        slug: 'sales',
        gridPosition: [0, 0],
        label: 'Sales',
        color: palette.anchor300,
        gradientColorB: palette.anchor200,
        activeColor: palette.teal500,
        activeGradientColorB: palette.anchor300,
        textColor: palette.sand100,
        slideDirection: [0, 0],
        tooltipTitle: 'Sales',
        tooltipSubhead: 'Win more jobs',
        bullets: ['Lead handling', 'Follow-up system', 'Conversion tracking'],
        description: 'Stop relying purely on word-of-mouth. We build a predictable lead-handling and follow-up system that tracks conversions and wins more jobs.',
        icon: icons.sales,
      },
      {
        id: 1,
        slug: 'operations',
        gridPosition: [0, 1],
        label: 'Ops',
        color: palette.gold500,
        gradientColorB: palette.gold300,
        activeColor: palette.gold700,
        activeGradientColorB: palette.gold500,
        textColor: palette.anchor900,
        slideDirection: [0, 0],
        tooltipTitle: 'Operations',
        tooltipSubhead: 'Run jobs clean',
        bullets: ['Schedule crews', 'Track production', 'Quality control'],
        description: 'Smooth out your production pipeline. From scheduling crews to strict quality control, we help you run jobs clean and on time.',
        icon: icons.ops,
      },
      {
        id: 2,
        slug: 'finance',
        gridPosition: [1, 0],
        label: 'Finance',
        color: palette.teal500,
        gradientColorB: palette.teal300,
        activeColor: palette.teal700,
        activeGradientColorB: palette.teal500,
        textColor: palette.sand100,
        slideDirection: [0, 0],
        tooltipTitle: 'Finance',
        tooltipSubhead: 'Know your numbers',
        bullets: ['Job costing', 'Cash visibility', 'Profit analysis'],
        description: 'Gain total financial clarity. We implement precise job costing and profit analysis so you always have real-time cash visibility.',
        icon: icons.finance,
      },
      {
        id: 3,
        slug: 'exit',
        gridPosition: [1, 1],
        label: 'Exit',
        color: palette.green500,
        gradientColorB: palette.green300,
        activeColor: palette.green700,
        activeGradientColorB: palette.green500,
        textColor: palette.sand100,
        slideDirection: [0, 0],
        tooltipTitle: 'Exit',
        tooltipSubhead: 'Exit on your terms',
        bullets: ['Clean financials', 'Diligence-ready', 'Valuation support'],
        description: 'Get diligence-ready. We clean up your financials and provide valuation support so you exit on your terms, for maximum value.',
        icon: icons.exit,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // LEVEL B: MIDDLE STRIPS — Systems teal gradient
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'layer-b',
    level: 'B',
    layout: 'row',
    cols: 3,
    depth: 5.5,
    align: 'center',
    blocks: [
      {
        id: 4,
        slug: 'one-os',
        label: 'OS',
        color: palette.teal700,
        gradientColorB: palette.teal500,
        activeColor: palette.anchor900,
        activeGradientColorB: palette.teal700,
        textColor: palette.sand100,
        slideDirection: [0, 0],
        tooltipTitle: 'One Operating System',
        tooltipSubhead: 'Everything connects',
        bullets: ['Lead → Review flow', 'Unified data', 'Single source of truth'],
        description: 'No more disconnected tools. We unify your data into a single source of truth, connecting your entire flow from lead to review.',
        icon: icons.system,
      },
      {
        id: 5,
        slug: 'one-team',
        label: 'Team',
        color: palette.teal500,
        gradientColorB: palette.teal300,
        activeColor: palette.teal700,
        activeGradientColorB: palette.teal500,
        textColor: palette.sand100,
        slideDirection: [0, 0],
        tooltipTitle: 'One Accountable Team',
        tooltipSubhead: 'Done-for-you execution',
        bullets: ['Not just advice', 'Implementation partner', 'Ongoing support'],
        description: 'We aren\'t just consultants offering advice. We are your implementation partner providing ongoing, done-for-you execution.',
        icon: icons.team,
      },
      {
        id: 6,
        slug: 'one-plan',
        label: 'Plan',
        color: palette.teal300,
        gradientColorB: palette.tealExLight,
        activeColor: palette.teal500,
        activeGradientColorB: palette.teal300,
        textColor: palette.anchor900,
        slideDirection: [0, 0],
        tooltipTitle: 'One Clear Plan',
        tooltipSubhead: 'Partner → Exit',
        bullets: ['Align', 'Transform', 'Scale'],
        description: 'A clear roadmap from partnership to IPO. We align our goals, transform your operations, and scale together.',
        icon: icons.plan,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // LEVEL C: BOTTOM TILES — Full brand spectrum
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'layer-c',
    level: 'C',
    layout: 'full',
    blocks: [
      {
        id: 7,
        slug: 'lead-to-review',
        label: 'Lead OS',
        color: palette.anchor900,
        gradientColorB: palette.anchor700,
        activeColor: palette.anchorDeep,
        activeGradientColorB: palette.anchor900,
        textColor: palette.sand100,
        tooltipTitle: 'Lead-to-Review OS',
        tooltipSubhead: 'End-to-end workflow',
        bullets: ['Demand', 'Sales', 'Production', 'Review'],
        description: 'An end-to-end workflow managing demand, sales, production, and reviews seamlessly.',
        icon: icons.flow,
      },
      {
        id: 8,
        slug: 'crm-marketing',
        label: 'CRM',
        color: palette.anchor700,
        gradientColorB: palette.anchor500,
        activeColor: palette.anchor900,
        activeGradientColorB: palette.anchor700,
        textColor: palette.sand100,
        tooltipTitle: 'CRM + Marketing Engine',
        tooltipSubhead: 'Trackable & repeatable',
        bullets: ['CRM installation', 'Pipeline management', 'Marketing auto'],
        description: 'Pipeline management and marketing automation that make your revenue trackable & repeatable.',
        icon: icons.contact,
      },
      {
        id: 9,
        slug: 'accounting',
        label: 'Acct',
        color: palette.teal700,
        gradientColorB: palette.teal500,
        activeColor: palette.tealDark,
        activeGradientColorB: palette.teal700,
        textColor: palette.sand100,
        tooltipTitle: 'Unified Accounting',
        tooltipSubhead: 'Financial clarity',
        bullets: ['Job costing', 'Reporting', 'Operating system link'],
        description: 'Connect your job costing directly to your operating system for complete reporting clarity.',
        icon: icons.ledger,
      },
      {
        id: 10,
        slug: 'revops',
        label: 'RevOps',
        color: palette.teal500,
        gradientColorB: palette.teal300,
        activeColor: palette.teal700,
        activeGradientColorB: palette.teal500,
        textColor: palette.sand100,
        tooltipTitle: 'RevOps Controls',
        tooltipSubhead: 'System becomes behavior',
        bullets: ['Governance', 'Playbooks', 'Adoption tracking'],
        description: 'Playbooks, governance, and adoption tracking to ensure your team actually uses the tools.',
        icon: icons.control,
      },
      {
        id: 11,
        slug: 'efficiency',
        label: 'Savings',
        color: palette.green700,
        gradientColorB: palette.green500,
        activeColor: palette.greenDark,
        activeGradientColorB: palette.green700,
        textColor: palette.sand100,
        tooltipTitle: 'Efficiency Savings',
        tooltipSubhead: 'Cut leaks',
        bullets: ['Reduce overhead', 'Smoother handoffs', 'Standardization'],
        description: 'Standardize handoffs, cut leaks, and reduce overhead to instantly boost your margins.',
        icon: icons.savings,
      },
      {
        id: 12,
        slug: 'shared-services',
        label: 'Services',
        color: palette.green500,
        gradientColorB: palette.green300,
        activeColor: palette.green700,
        activeGradientColorB: palette.green500,
        textColor: palette.sand100,
        tooltipTitle: 'Shared Services',
        tooltipSubhead: 'Dedicated bench',
        bullets: ['Build support', 'Maintenance', 'Keep stack running'],
        description: 'Access our dedicated support bench to maintain and optimize your tech stack.',
        icon: icons.services,
      },
      {
        id: 13,
        slug: 'scale',
        label: 'Scale',
        color: palette.gold700,
        gradientColorB: palette.gold500,
        activeColor: palette.goldDark,
        activeGradientColorB: palette.gold700,
        textColor: palette.anchor900,
        tooltipTitle: 'Scale + Leverage',
        tooltipSubhead: 'Group power',
        bullets: ['8-12 businesses', 'Leverage economies', 'Unified growth'],
        description: 'Combine the power of 8–12 businesses for unified growth and massive economies of scale.',
        icon: icons.growth,
      },
      {
        id: 14,
        slug: 'exit-options',
        label: 'Exit',
        color: palette.gold500,
        gradientColorB: palette.gold300,
        activeColor: palette.gold700,
        activeGradientColorB: palette.gold500,
        textColor: palette.anchor900,
        tooltipTitle: 'Institutional Exit Options',
        tooltipSubhead: 'Premium exit positioning',
        bullets: ['Audit logs', 'Data room', 'Transferability'],
        description: 'Audit logs and clean data rooms that position your business for a premium public exit.',
        icon: icons.exitReady,
      },
    ],
  },
];

export const classicVariant: StackVariant = {
  id: 'classic',
  name: 'Classic',
  description: 'Original 15-block stack: Sales, Operations, Finance, Exit at the top.',
  layers,
  // No overrides — uses config.ts defaults
};
